version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "5000:5000"      
    networks:
      - kafka-network
      
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-network


  kafka-connect:
    image: confluentinc/cp-kafka-connect
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    networks:
      - kafka-network

      
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    depends_on:
      - kafka
      - zookeeper
      - kafka-connect
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "kafka-connect:8083"
      KAFKA_REST_LISTENERS: "http://kafka-rest:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://kafka-rest:8081"
      KAFKA_REST_HOST_NAME: "kafka-rest"
    networks:
      - kafka-network

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    depends_on:
      - kafka
      - zookeeper
      - kafka-rest
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:8082"
      PROXY: "true"
    networks:
      - kafka-network

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    depends_on:
      - kafka
      - zookeeper
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "shutc1secret"   
    networks:
      - kafka-network
      
networks:
    kafka-network:
